name: Eleventy Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Eleventy Site
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          publish-dir: ./_site
